version: '3.7'
services:
  app:
    build:
      context: ./app
    restart: always
    stop_signal: SIGKILL
    environment:
      - POSTGRES_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${CONTAINER_NAME}:5432/${POSTGRES_DB}
    ports:
      - "80:80"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: ${CONTAINER_NAME}
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data


volumes:
  db: